image: $CI_REGISTRY/r3/docker/julia-custom

stages:
  - build

variables:
    GIT_STRATEGY: clone

.global_settings: &global_settings
  tags:
   - artenolis
   - slave01

.global_testing: &global_testing
  script:
    - $ARTENOLIS_SOFT_PATH/julia/$JULIA_VER/bin/julia --color=yes --project=@. -e 'import Pkg; Pkg.test(; coverage = true)'

.global_testing_win: &global_testing_win
  script:
    - Invoke-Expression $Env:ARTENOLIS_SOFT_PATH"\julia\"$Env:JULIA_VER"\bin\julia --color=yes --project=@. -e 'import Pkg; Pkg.test(; coverage = true)'"

linux julia v1.5:
  stage: build
  variables:
    JULIA_VER: "v1.5.3"
  <<: *global_settings
  <<: *global_testing

windows10:
  stage: build
  tags:
    - artenolis
    - windows10
  variables:
    JULIA_VER: "v1.5.3"
  <<: *global_testing_win

windows8:
  stage: build
  tags:
    - artenolis
    - windows8
  variables:
    JULIA_VER: "v1.5.3"
  <<: *global_testing_win