using Pkg

Pkg.add("SOM")
Pkg.add("RDatasets")
Pkg.add("RCall")
Pkg.add("PyCall")
Pkg.add("VegaLite")
Pkg.add("FreqTables")
Pkg.add("Distances")
Pkg.add("Plotly")
Pkg.add("Plots")
Pkg.add("ProgressMeter")
Pkg.add("Distributions")
Pkg.add("TensorToolbox")
Pkg.add("DistributedArrays")
Pkg.add("StatsBase")
Pkg.add("FCSFiles")
Pkg.add("DataFrames")
Pkg.add("CSV")
Pkg.add("StatsPlots")
Pkg.add("Statistics")
Pkg.add("MultivariateStats")
Pkg.add("FileIO")
Pkg.add("JuliaInterpreter")
Pkg.add("Distributed")
Pkg.add("PyPlot")
Pkg.add("GigaSOM")
Pkg.add("Test")
